project:
  name: Singlestore alerts by AppsCode
  shortName: Singlestore alerts
  url: https://github.com/appscode/alerts
  description: Singlestore alerts for KubeDB
  app: Singlestore alerts
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: singlestore
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.19+
release:
  name: singlestore
  namespace: demo
