project:
  name: Qdrant alerts by AppsCode
  shortName: Qdrant alerts
  url: https://github.com/appscode/alerts
  description: Qdrant alerts for KubeDB
  app: Qdrant alerts
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: qdrant
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.19+
release:
  name: qdrant
  namespace: demo
