{{ $app := (include "oracle-alerts.fullname" .) }}

{{ if (include "oracle-alerts.alertsEnabled" .Values.form.alert.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ $app }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "oracle-alerts.labels" . | nindent 4 }}
{{- if .Values.form.alert.labels }}
    {{- toYaml .Values.form.alert.labels | nindent 4 }}
{{- end }}
{{- if .Values.form.alert.annotations }}
  annotations:
    {{- toYaml .Values.form.alert.annotations | nindent 4 }}
{{- end }}
spec:
  groups:
  {{ with .Values.form.alert.groups.database -}}
  {{ if (include "oracle-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: oracle.database.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ if (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled .rules.oracleInstanceDown.enabled .rules.oracleInstanceDown.severity)) -}}
    - alert: OracleInstanceDown
      expr: up{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"} == 0
      for: {{ .rules.oracleInstanceDown.duration }}
      labels:
        severity: {{ .rules.oracleInstanceDown.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Oracle instance down (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Oracle instance is down on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{end -}}
    {{ if (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled .rules.oracleServiceDown.enabled .rules.oracleServiceDown.severity)) -}}
    - alert: OracleServiceDown
      expr: sum by (service) (up{job="{{ $app }}-stats",namespace="{{ $.Release.Namespace }}"}) == 0
      for: {{ .rules.oracleServiceDown.duration }}
      labels:
        severity: {{ .rules.oracleServiceDown.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Oracle service down (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Oracle service is down on {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ if (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled .rules.oracleRestarted.enabled .rules.oracleRestarted.severity)) -}}
    - alert: OracleRestarted
      expr: oracledb_uptime_uptime_seconds{job="{{- $app -}}-stats",namespace="{{ $.Release.Namespace }}"} < {{ .rules.oracleRestarted.val }}
      for: {{ .rules.oracleRestarted.duration }}
      labels:
        severity: {{ .rules.oracleRestarted.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Oracle restarted (instance {{`{{`}} $labels.pod {{`}}`}})
        description: "Oracle restarted\n  {{`{{`}} $labels.pod {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{end -}}
    {{ if (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled .rules.diskUsageHigh.enabled .rules.diskUsageHigh.severity)) -}}
    - alert: DiskUsageHigh
      expr: |
        (kubelet_volume_stats_used_bytes{job=~"kubelet"} / on(persistentvolumeclaim) group_left(pod) (
          kubelet_volume_stats_capacity_bytes{job=~"kubelet"} + on(persistentvolumeclaim) group_left(pod)
          kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~"{{ $.Release.Name }}-.+$", namespace=~"{{ $.Release.Namespace }}"}
        )) * 100 > {{ .rules.diskUsageHigh.val }}
      for: {{ .rules.diskUsageHigh.duration }}
      labels:
        severity: {{ .rules.diskUsageHigh.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Persistent Volume Usages in instance {{`{{`}} $labels.instance {{`}}`}}
        description: "Persistent Volume Usages\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
    {{ if (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled .rules.diskAlmostFull.enabled .rules.diskAlmostFull.severity)) -}}
    - alert: DiskAlmostFull
      expr: |
        (kubelet_volume_stats_used_bytes{job=~"kubelet"} / on(persistentvolumeclaim) group_left(pod) (
        kubelet_volume_stats_capacity_bytes{job=~"kubelet"} + on(persistentvolumeclaim) group_left(pod)
        kube_pod_spec_volumes_persistentvolumeclaims_info{pod=~"{{ $.Release.Name }}-.+$", namespace=~"{{ $.Release.Namespace }}"}
        )) * 100 > {{ .rules.diskAlmostFull.val }}
      for: {{ .rules.diskAlmostFull.duration }}
      labels:
        severity: {{ .rules.diskAlmostFull.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: Persistent Volume Usages in instance {{`{{`}} $labels.instance {{`}}`}}
        description: "Persistent Volume Usages\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}


  {{ with .Values.form.alert.groups.provisioner -}}
  {{ if (include "oracle-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: oracle.provisioner.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ if (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled .rules.appPhaseNotReady.enabled .rules.appPhaseNotReady.severity)) -}}
    - alert: KubeDBOraclePhaseNotReady
      expr: kubedb_com_oracle_status_phase{phase="NotReady",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ .rules.appPhaseNotReady.duration }}
      labels:
        severity: {{ .rules.appPhaseNotReady.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB Oracle Phase NotReady (oracle {{`{{`}} $labels.oracle {{`}}`}})
        description: "KubeDB Oracle Phase not ready on {{`{{`}} $labels.oracle {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ if (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled .rules.appPhaseCritical.enabled .rules.appPhaseCritical.severity)) -}}
    - alert: KubeDBOraclePhaseCritical
      expr: kubedb_com_oracle_status_phase{phase="Critical",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ .rules.appPhaseCritical.duration }}
      labels:
        severity: {{ .rules.appPhaseCritical.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: KubeDB Oracle Phase Critical (oracle {{`{{`}} $labels.oracle {{`}}`}})
        description: "KubeDB Oracle Phase Critical {{`{{`}} $labels.oracle {{`}}`}}\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}


  {{ with .Values.form.alert.groups.opsManager -}}
  {{ if (include "oracle-alerts.alertGroupEnabled" (list $.Values.form.alert.enabled .)) -}}
  - name: oracle.opsManager.{{ $.Release.Namespace }}.{{ $app }}.rules
    rules:
    {{ if (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled .rules.opsRequestOnProgress.enabled .rules.opsRequestOnProgress.severity)) -}}
    - alert: KubeDBOracleOpsRequestOnProgress
      expr: ops_kubedb_com_oracleopsrequest_status_phase{phase="Progressing",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ .rules.opsRequestOnProgress.duration }}
      labels:
        severity: {{ .rules.opsRequestOnProgress.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: OracleOpsRequest on progress (oracleopsrequest {{`{{`}} $labels.oracleopsrequest {{`}}`}})
        description: "OracleOpsRequest {{`{{`}} $labels.oracleopsrequest {{`}}`}} is in progressressing status\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ if (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled .rules.opsRequestStatusProgressingToLong.enabled .rules.opsRequestStatusProgressingToLong.severity)) -}}
    - alert: KubeDBOracleOpsRequestStatusProgressingToLong
      expr: ops_kubedb_com_oracleopsrequest_status_phase{phase="Progressing",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ .rules.opsRequestStatusProgressingToLong.duration }}
      labels:
        severity: {{ .rules.opsRequestStatusProgressingToLong.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: OracleOpsRequest is in progressing status for too long (oracleopsrequest {{`{{`}} $labels.oracleopsrequest {{`}}`}})
        description: "OracleOpsRequest {{`{{`}} $labels.oracleopsrequest {{`}}`}} is in progressing status for too long\n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{ end -}}
    {{ if (include "oracle-alerts.alertEnabled" (list $.Values.form.alert.enabled .enabled .rules.opsRequestFailed.enabled .rules.opsRequestFailed.severity)) -}}
    - alert: KubeDBOracleOpsRequestFailed
      expr: ops_kubedb_com_oracleopsrequest_status_phase{phase="Failed",app="{{ $app }}",namespace="{{ $.Release.Namespace }}"} == 1
      for: {{ .rules.opsRequestFailed.duration }}
      labels:
        severity: {{ .rules.opsRequestFailed.severity }}
        {{- include "oracle-alerts.alertLabels" $ | nindent 8 }}
      annotations:
        summary: OracleOpsRequest failed (oracleopsrequest {{`{{`}} $labels.oracleopsrequest {{`}}`}})
        description: "OracleOpsRequest {{`{{`}} $labels.oracleopsrequest {{`}}`}} failed \n  VALUE = {{`{{`}} $value {{`}}`}}\n  LABELS = {{`{{`}} $labels {{`}}`}}"
    {{- end }}
  {{ end -}}
  {{ end -}}
{{ end }}