apiVersion: v2
name: openfga-alerts
description: A Helm chart for OpenFGA Alert Rules
type: application
version: v2025.1.0
appVersion: v0.1.0
home: https://github.com/ops-center/alerts
icon: https://openfga.dev/img/openfga-icon.svg
sources:
- https://github.com/ops-center/alerts
maintainers:
- name: appscode
  email: support@appscode.com
