project:
  name: MSSQLServer alerts by AppsCode
  shortName: MSSQLServer alerts
  url: https://github.com/appscode/alerts
  description: MSSQLServer alerts for KubeDB
  app: MSSQLServer alerts
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: mssqlserver
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.19+
release:
  name: mssqlserver
  namespace: demo
